# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    evento: 'Feria Matemática 2020'
    actividad1: Braille
    actividad1m: 5
    actividad1v: 5
    actividad2: Canguro
    actividad2m: 5
    actividad2v: 5
    actividad3: Casino
    actividad3m: 5
    actividad3v: 5
    actividad4: CIGA
    actividad4m: 4
    actividad4v: 4
    actividad5: CIMAT
    actividad5m: 4
    actividad5v: 4
    actividad6: Club de Mate
    actividad6m: 5
    actividad6v: 5
    actividad7: DIMATE
    actividad7m: 6
    actividad7v: 6
    actividad8: Espejos y reflejos
    actividad8m: 5
    actividad8v: 5
    actividad9: ENES
    actividad9m: 3
    actividad9v: 3
    actividad10: Gatosordo
    actividad10m: 5
    actividad10v: 5
    actividad11: IFM
    actividad11m: 4
    actividad11v: 4
    actividad12: IRyA
    actividad12m: 4
    actividad12v: 4
    actividad13: Matemagia
    actividad13m: 3
    actividad13v: 3
    actividad14: Mosaicos (Penrose)
    actividad14m: 6
    actividad14v: 6
    actividad15: Torres de Hanói
    actividad15m: 5
    actividad15v: 5
    actividad16: Logística
    actividad16m: 3
    actividad16v: 3

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
